config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'tests#index'

  resources :tests do
    resources :questions
  end

  # resource :account

  # resource :account, controller: :account

  # resources :tests, only: %i[index show]

  # resources :tests do
  #   resources :questions
  # end

  # resources :tests do
    # resources :questions, shallow: true # сокращает url
  # end

# -------------- ***** ------------------
  # GET /tests/beginner  # чтобы реализовать такие урлы см ниже
  # POST /tests/1/start

  # resources :tests do
  #   get :beginner, on: :collection

  #   member do
  #     post :start
  #   end
  # end
# -------------- ***** ------------------

  # get '/test', to: 'tests#index'
  # get '/test/:id', to: 'tests#show', as: :test
  # get '/test(/:id)', to: 'tests#show', as: :test # необязательный параметр id

  get '/tests/:id/start', to: 'tests#start', as: :start
  # get '/tests/:id/start', to: 'tasks#start'
  # get '/tests/:test_id/questions/:id(.:format)', to: 'questions#show'

  # match '/tests/:id', to: 'tests#create', via: %i[post put]
  # match '/tests/:id', to: 'tests#create', via: :all

  # /tests/backend/ruby
  # get '/tests/:category/:title', to: 'tests#search'

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers

  validates :body, presence: true

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_question, only: [:show, :destroy, :update, :edit]
  before_action :find_test, only: [:new, :index, :create, :show, :destroy, :update, :edit]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show
    @question
  end

  def index
    @questions = @test.questions
  end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)
    respond_to do |format|
      if @question.save
        format.html { redirect_to @test, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @test, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to @test, notice: 'Question was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def rescue_with_question_not_found
    render plain: "404. Question was not found"
  end

  def find_question
    @question = Question.find(params[:id])
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def question_params
    params.require(:question).permit(:body)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(test_title)
    if current_page?(new_test_question_path)
      "Create New #{test_title} Question"
    else
      "Edit #{test_title} Question"
    end
  end
end

app/views/questions/_form.html.erb
<%= form_with(model: [@test, @question], local: true) do |form| %>
  <div class="">
    <%= form.label :body %>
    <%= form.text_area :body, class: "" %>
  </div>

  <div class="">
    <%= form.submit class: "" %>
    <%= link_to 'Back', test_path(@test), class: "" %>
  </div>
<% end %>
</br>

app/views/questions/_test-questions.html.erb
<h4>Questions</h4>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Body</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.id %></td>
        <td><%= question.body %></td>
        <td><%= link_to 'Show', test_question_path(@test, question) %></td>
        <td><%= link_to 'Edit', edit_test_question_path(@test, question) %></td>
        <td><%= link_to 'Destroy', test_question_path(@test, question), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/questions/edit.html.erb
<h1><%= question_header(@test.title) %></h1>

<%= render 'form', question: @question %>

app/views/questions/index.html.erb
<h3>Questions</h3>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @questions.each do |question| %>
    <tr>
      <td><%= question.id %></td>
      <td><%= question.body %></td>
      <td><%= link_to 'Show', test_question_path(@test, question) %></td>
      <td><%= link_to 'Delete', test_question_path(@test, question), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Back to test page', test_path(@test.id) %>

app/views/questions/new.html.erb
<h1><%= question_header(@test.title) %></h1>
<form action="/tests/<%= @test.id %>/questions" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	<p>
		<label for="body">Question:</label>
		<input type="text" name="question[body]" id="question_id">
	</p>
	<br>
	<input type="submit" value="create">
    <%= link_to 'Back to test', @test %>

</form>

app/views/questions/show.html.erb
<p><%= @question.body %></p>
</br>
<%= link_to 'Back to test page', test_path(@test) %>